fixtures:
  repositories:
    common:
      repo: 'git://github.com/ghoneycutt/puppet-module-common.git'
      ref: 'v1.3.0'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
  symlinks:
    types: "#{source_dir}"
